version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "coworking-analytics-repository"
    AWS_ACCOUNT_ID: "031750745573"
    AWS_REGION: "us-east-1"
    IMAGE_TAG: "latest"
    CODEBUILD_BUILD_NUMBER: "v1.0.0"
  
phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade awscli
      - aws configure set region $AWS_REGION

  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER .
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

      - echo "Setting up Kubeconfig..."
      - aws eks --region $AWS_REGION update-kubeconfig --name my-cluster
      - kubectl apply -f deployment/configmap.yaml
      - kubectl apply -f deployment/secret.yaml
      - kubectl apply -f deployment/coworking.yaml

  post_build:
    commands:
      - echo "Tagging the Docker image..."
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Pushing the Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

      - echo "Deploying to Kubernetes..."
      - kubectl rollout restart deployment/coworking
      - kubectl get pods
      - echo "Deployment Complete"
